### PR TITLE
iTunes Radio Support

### PR DESCRIPTION
**Pull request by ianb821**
Added the same support that was previously created for Pandora Radio to iTunes Radio.  Now when pressing the "star" button on the now playing song in iTunes Radio, an option to open the current song in Spotify is presented.  Works just it does for Pandora.

### CODE REVIEW

**Comment by AdiSai** [comment]
@ianb821 How?

**Comment by AdiSai** [comment]
Really @Haifisch?

**Comment by Haifisch** [comment]
Adi, this is not a wiki page.

**Comment by AdiSai** [comment]
How did you do that @Haifisch?

**Comment by Haifisch** [comment]
I am a HASHBANG Admin. If you need to talk to me, do so on IRC, not here. It spams peoples emails.

**Pull request merged**
